pool:
  vmImage: 'Ubuntu 16.04'
   
steps:
 
- script: dotnet build 'FunctionApp1.sln' --configuration $(buildConfiguration)
  displayName: 'Build solution'
     
- script: dotnet test 'XUnitTestProject1' --configuration $(buildConfiguration) --logger trx
  displayName: 'Run unit tests'
 
- task: PublishTestResults@2
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'
 
- script: dotnet publish 'FunctionApp1/FunctionApp1.csproj' --configuration $(buildConfiguration) --output '$(Build.ArtifactStagingDirectory)/app'
  displayName: 'Package function app'
 
- task: PublishBuildArtifacts@1
  displayName: 'Publishing app artifact'
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)/app'
    artifactName: app